apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-petclinic-frontend
  labels:
    app: api-gateway

spec:
  template:
    metadata:
      name: pod-petclinic-frontend
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: awscicd/spring-petclinic-api-gateway
          command: ["./dockerize","-wait=tcp://petclinic-service-discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
          ports:
            - containerPort: 8080

  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
