apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-petclinic-servers
  labels:
    app: mng-servers

spec:
  template:
    metadata:
      name: pod-petclinic-servers
      labels:
        app: mng-servers
    spec:
      containers:
        - name: config-server
          image: awscicd/spring-petclinic-config-server
          ports:
            - containerPort: 8888

        - name: discovery-server
          image: awscicd/spring-petclinic-discovery-server
          command: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
          ports:
            - containerPort: 8761

        - name: admin-server
          image: awscicd/spring-petclinic-admin-server
          command: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
          ports:
            - containerPort: 9090

  replicas: 1
  selector:
    matchLabels:
      app: mng-servers

