apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-servers
spec:
  type: NodePort
  ports:
    - name: "8761"
      targetPort: 8761
      port: 8761
      nodePort: 30761
    - name: "8888"
      targetPort: 8888
      port: 8888
      nodePort: 30888
    - name: "9090"
      targetPort: 9090
      port: 9090
      nodePort: 30090
  selector:
    app: mng-servers
