apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-config-server
spec:
  type: NodePort
  ports:
    - name: "8888"
      targetPort: 8888
      port: 8888
      nodePort: 30888
  selector:
    app: petclinic-config-server
