apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-servers
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30080
  selector:
    app: api-gateway
